name: hdc_dino
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - cython
  - pillow
  - tqdm
  - pyyaml
  - requests
  - psutil
  - fsspec=2023.6.0
  - importlib-metadata
  - importlib_resources
  - pytorch=2.4.1
  - torchvision=0.20.0
  - pytorch-cuda=12.4
  - typing_extensions
  - traitlets
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - ninja
  - gmpy2
  - sympy
  - zstandard
  - tornado
  - setuptools
  - wheel
  - pip
  - pip:
      - addict==2.4.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - git-filter-repo==2.47.0
      - huggingface-hub==0.29.3
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - ninja==1.11.1.3
      - opencv-python==4.11.0.86
      - pycocotools==2.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - safetensors==0.5.3
      - termcolor==2.4.0
      - timm==1.0.15
      - tomli==2.2.1
      - tqdm==4.67.1
      - yapf==0.43.0
      - zipp==3.20.2
